[package]
name = "arch-clean"
version = "0.1.0"
authors = ["Mario Ortiz Manero <marioortizmanero@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1.4"
anyhow = "1.0.34"
tokio-async-std = "1.5.3"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
